# Generated by Django 2.0 on 2019-05-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='removed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
