# Generated by Django 2.0 on 2019-05-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190514_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='signature',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
