# Generated by Django 2.0 on 2019-05-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telphone',
            new_name='telephone',
        ),
    ]
